# Generated by Django 6.0.2 on 2026-02-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en la página de inicio'),
        ),
    ]
