# Generated by Django 6.0.2 on 2026-02-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0002_alter_contact_created_at_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactado',
            field=models.BooleanField(default=False, verbose_name='¿El contacto ha sido atendido?'),
        ),
    ]
