# Generated by Django 6.0.2 on 2026-02-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en la página de inicio'),
        ),
    ]
