# Generated by Django 6.0.2 on 2026-02-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='courses/images/', verbose_name='Imagen del curso'),
        ),
    ]
